### ISSUE TITLE
Webhooks for Appoinment Created / Updated / Deleted

### ISSUE THREAD

**Issue by nick-goloborodko** [microsoft/bookings-samples#5]
Hi,

Is it possible to setup somethign like a webhook to trigger on new appoinments being Added / Updated / Deleted?

I'm looking to integrate Microsoft bookings with a lead automation system and will need that sort of functionality for it to work.

Thanks,
Nick

**Comment by fpintos** [comment]
Thanks for the suggestion Nick. I'll forward it to the team.

In the meantime, it will be interesting to post this as an idea in the [Microsoft Bookings Uservoice forum](https://outlook.uservoice.com/forums/314907).

Another option would be to see if this can be already accomplished with the [Graph Webhooks](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/webhooks). I haven't tried it myself, but since Booking appointments are effectively stored as events, it is possible this already works.

For example, you should be able to access booking appointments as "normal" events with URLs like this: https://graph.microsoft.com/v1.0/users('businessId@yourcompany.com')/events

So I'm wondering if the Graph Webhook will work with these as well. Their doc talks about the /me/events, but not /users('...')/events, so I'm not 100% sure.

**Comment by hemanthj** [comment]
Any update on this feature?  This would be a great use-case for reporting.

**Comment by LarsKemmann** [comment]
I'm also in need of this feature, any progress?

**Comment by jfacoustic** [comment]
Same here.

**Comment by sven-borden** [comment]
@fpintos can you confirm if it is possible to use the Graph Webhook ?
Thanks

**Comment by fpintos** [comment]
@sven-borden @jfacoustic @LarsKemmann I haven't worked with the Bookings API in a while. I suggest using https://developer.microsoft.com/en-us/graph/support to submit questions and feature requests. Thanks.
